### PR TITLE
Adding new fields, as of iTunes 12

### PR DESCRIPTION
**Pull request by deluan**

### CODE REVIEW

**Comment by dhowden** [comment]
Awesome, thanks.

If you can run it through `go fmt` I'll merge it in.

**Comment by deluan** [comment]
Sure, there you go.

**Comment by deluan** [comment]
Do you rather have me rebase all these into one commit? I could recreate the PR. Let me know.

**Comment by dhowden** [comment]
Squashed into one would probably be better I think (then we get rid of the "go fmt" commit 👍).

**Pull request closed without merging**
